name: soft-deletable-bundle-CI
on:
  [push, pull_request]
jobs:
  build_php_7_4:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: mysql version
        run:  sudo systemctl enable mysql.service
        
          
      - name: mysql version
        run:  sudo systemctl start mysql.service
  
          
      - name: mysql version
        run: mysql --version
        
      - name: mysql test
        run: mysql -uroot -proot -h localhost test
