name: soft-deletable-bundle-CI
on:
  [push, pull_request]
jobs:
  build_php_7_4:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: setting mysql
        run: |
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          mysql -uroot -proot -h localhost -e "CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;"

      - name: test mysql
        run: mysql -uroot -proot -h localhost test
