name: soft-deletable-bundle-CI
on:
  [push, pull_request]
jobs:
  build-php-7-4:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install
#      too slow
#      - uses: actions/upload-artifact@v2
#        with:
#          name: build-php-7-4
#          path: ${{ github.workspace }}
#          retention-days: 1

  build-php-8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install

  check-code-php-7-4:
    runs-on: ubuntu-latest
    needs: [ build-php-7-4 ]
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install

      - name: cs-check
        run: composer cs-check

      - name: phpstan
        run: composer phpstan

  check-code-php-8:
    runs-on: ubuntu-latest
    needs: [ build-php-8 ]
    steps:
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install

      - name: cs-check
        run: composer cs-check

      - name: phpstan
        run: composer phpstan

  tests-php-7-4:
    runs-on: ubuntu-latest
    needs: [ build-php-7-4 ]
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2

      - name: composer install
        run: composer install

      - name: setting mysql
        run: |
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          mysql -uroot -proot -h localhost -e "CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;"

      - name: phpunit
        run: composer phpunit

  tests-php-8:
    runs-on: ubuntu-latest
    needs: [ build-php-8 ]
    steps:
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install

      - name: setting mysql
        run: |
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          mysql -uroot -proot -h localhost -e "CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;"

      - name: phpunit
        run: composer phpunit
